output.max_controls;
mw = sol.states.mw.value;
fprintf('m_w     = %f\n',mw(10));
khip = sol.states.khip.value;
fprintf('k_hip   = %f\n',khip(10));
kknee = sol.states.kknee.value;
fprintf('k_knee  = %f\n',kknee(10));
kankle = sol.states.kankle.value;
fprintf('k_ankle = %f\n',kankle(10));
bankle = sol.states.bankle.value;
fprintf('b_ankle = %f\n',bankle(10));
figure();
output.control_output;
figure();
output.plot_lw;
%figure();
%output.animation(sol,times);
